setting Intel bach as default compiler for Levante. Replacing env/lev…
FESOM/fesom2 pull request #440
Opened 2023-03-21 21:10 UTC by dsidoren

…ante.dkrz.de/shell.nvhpc->shell will allow to compile with NV & OpenACC support

2023-03-21 21:14 UTC, suvarchal requested changes
may be multio directory pointing to a user's directory is not elegant?

2023-03-21 21:14 UTC, suvarchal commented on env/levante.dkrz.de/shell
does it make sense to add multio directories to it ?

2023-03-23 20:25 UTC, koldunovn approved these changes

2023-03-23 21:07 UTC, suvarchal approved these changes
moving on for now

2023-03-23 21:07 UTC, suvarchal commented on env/levante.dkrz.de/shell
resolving for now as it is harmless

2023-03-23 21:07 UTC, merged