added heat content computation as required by destinE GSV. Shall be a…
FESOM/fesom2 pull request #660
Opened 2024-12-19 14:02 UTC by dsidoren

…ctivated in namelist.io as ldiag_destinE=.TRUE.

2024-12-19 21:29 UTC, JanStreffing requested changes

2024-12-19 21:29 UTC, JanStreffing commented on config/namelist.io
> +ldiag_destinE    =.false.
Would be great to use a name that tells the user what diagnostic will be created.

2024-12-19 21:29 UTC, JanStreffing commented on src/io_meandata.F90
> -  logical, save                  :: lnextGEMS=.FALSE.
Same for this one.

2025-01-20 08:36 UTC, sebastianbeyer commented on src/io_meandata.F90
> -  logical, save                  :: lnextGEMS=.FALSE.
when I try to run this with `ldiag_destinE=.TRUE.`, I get the following:

```
  --> FESOM STARTS TIME LOOP
 Updating SSS restoring data for month                1
  --check opt_visc--> Mean Ratio Resol/Rrossby =    5.0000000000000000
 Subroutine exchange_nod3D not implemented for           3 layers.
 Adding the MPI datatypes is easy, see oce_modules.F90.
 Run finished unexpectedly!
--------------------------------------------------------------------------
MPI_ABORT was invoked on rank 2 in communicator MPI_COMM_WORLD
  Proc: [[10799,1],2]
  Errorcode: 1
```

2025-01-23 20:05 UTC, sebastianbeyer commented
replaced by #673

2025-01-23 20:05 UTC, closed without merging