Abort model cleanly in ifsinterface and standalone on errors
FESOM/fesom2 pull request #661
Opened 2024-12-23 10:21 UTC by suvarchal

Some of old features lost in my branches that didn't make it into main, part 1.

- clean and exit model with par_ex instead of abort, this avoids a few annoying model hanging in ifs_interface.
- checks for namelists exist and show line where error happens and abort cleanly. 

TODO in another PR:
- model stop with par_ex should also be used consistently in checks should also be used in cvmix routines and ib routines. 
- add namelist checks in all other modules in style similar to this PR

2025-01-13 20:40 UTC, JanStreffing requested changes
Excellent changes. This should make missing namelists etc. easier to catch. I have just a few small changes requested.

2025-01-13 20:40 UTC, JanStreffing commented on src/gen_modules_partitioning.F90
> +! changes are easy but need to be tested with coupled configurations
Does that mean changes are were easy to make or would be easy?

2025-01-13 20:40 UTC, JanStreffing commented on src/oce_mesh.F90
> + !call MPI_Abort(MPI_COMM_FESOM, 1, ierror) # dont call abort here yet called bellow
Keep or remove fully

2025-01-14 13:34 UTC, suvarchal commented on src/gen_modules_partitioning.F90
> +! changes are easy but need to be tested with coupled configurations
It handles core parts and there are other parts like ice modules, blowup that may need more inspection on aborts, clean kind to stop normally vs really abort kind. this can be easy to do once we go through those parts, but i would leave it here for now, going into all those parts to me is another issue.  @JanStreffing  thanks for confirming communicator in oifs-fesom case, then nothing about that configuration to worry about with these changes.

2025-01-14 13:34 UTC, suvarchal commented on src/oce_mesh.F90
> + !call MPI_Abort(MPI_COMM_FESOM, 1, ierror) # dont call abort here yet called bellow
removed

2025-01-14 13:45 UTC, JanStreffing commented on src/gen_modules_partitioning.F90
> +! changes are easy but need to be tested with coupled configurations
i want to do one small test with OpenIFS-FESOM2 before I merge.

2025-01-15 23:56 UTC, JanStreffing approved these changes

2025-01-15 23:56 UTC, merged